name: Release

on:
  push:
    paths:
      - 'CHANGELOG.md'
  workflow_dispatch:

jobs:
  create_release:

    permissions:
      contents: write # Required to update releases
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read pubspec.yaml
        id: pubspec
        uses: nichmor/minimal-read-yaml@v0.0.2
        with:
          config: "./pubspec.yaml"

      - name: Get Release Notes
        id: release_notes
        uses: kiyoon/parse-changelog-action@v1
        with:
          changelog-file-path: CHANGELOG.md
          version: ${{ steps.pubspec.outputs['version'] }}

      - name: Get Tag
        run: |
          echo "NEW_TAG=v${{ steps.pubspec.outputs['version'] }}" >> $GITHUB_ENV

      - name: Create Tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.NEW_TAG}`,
              sha: context.sha
            })

      - name: Push Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.pubspec.outputs['version'] }}
          commit: ${{ github.sha }}
          body: ${{ steps.release_notes.outputs.body }}
