name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: 'v{{version}}'

jobs:
  publish:

    permissions:
      id-token: write # Required for authentication using OIDC
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Get dependencies
        run: flutter pub get

      # This produces too many warnings right now
      # Run linter
      # - name: Analyze
      #   run: flutter analyze

      - name: Run tests
        run: flutter test
        
      - name: Get pub.dev credentials
        uses: flutter-actions/setup-pubdev-credentials@v1

      - name: Check Publish Warnings
        run: flutter pub publish --dry-run

      - name: Publish Package
        run: flutter pub publish -f
