name: Publish to pub.dev

on:
  push:
  #  branches: ["main"] # publishing only allowd from 'tag' refType
   tags:
     - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
