name: Publish to pub.dev

on:
  push:
   tags:
     - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  publish:

    permissions:
      contents: write
      id-token: write # Required for authentication using OIDC
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Read pubspec for version number
      - name: Get Version
        id: version
        uses: KJ002/read-yaml@main
        with:
          file: "./pubspec.yaml"
          key-path: '["version"]'

      # Get Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          channel: "stable"

      # Get Flutter dependencies
      - name: Install dependencies
        run: flutter pub get

      # This produces too many warnings
      # - name: Analyze
      #   run: flutter analyze

      - name: Run tests
        run: flutter test
        
      - uses: flutter-actions/setup-pubdev-credentials@v1

      - name: Check Publish Warnings
        run: flutter pub publish --dry-run

      - name: Publish Package
        run: flutter pub publish -f

      # Create a release in GitHub
      - name: Create Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/bundle/release/*.aab
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.version.outputs.data }}
          commit: ${{ github.sha }}
