name: Publish to pub.dev

on:
  push:
   branches: ["main"]
   tags:
     - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Setup Pub Credentials
      #   shell: bash
      #   env:
      #     PUB_DEV_ACCESS_TOKEN: ${{ secrets.PUB_DEV_ACCESS_TOKEN }}
      #     PUB_DEV_REFRESH_TOKEN: ${{ secrets.PUB_DEV_REFRESH_TOKEN }}
      #     PUB_DEV_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_TOKEN_ENDPOINT }}
      #     PUB_DEV_TOKEN_EXPIRATION: ${{ secrets.PUB_DEV_TOKEN_EXPIRATION }}
      #   run: |
      #     sh ./scripts/pub_login.sh  

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      # This produces too many warnings
      # - name: Analyze
      #   run: flutter analyze

      - name: Run tests
        run: flutter test
        
      - name: 'Publish'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_DEV_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_DEV_REFRESH_TOKEN }}

      # - name: Check Publish Warnings
      #   run: pub publish --dry-run

      # - name: Publish Package
      #   run: pub publish -f
