name: Publish to pub.dev

on:
  push:
   tags:
     - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  publish:

    permissions:
      contents: write
      id-token: write
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      # This produces too many warnings
      # - name: Analyze
      #   run: flutter analyze

      - name: Run tests
        run: flutter test
        
      - uses: flutter-actions/setup-pubdev-credentials@v1
      
      - name: Check Publish Warnings
        run: pub publish --dry-run

      - name: Publish Package
        run: pub publish -f
